import type { NextPage } from 'next';
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import SocketIO from 'socket.io-client'
import styles from '../styles/Home.module.css';
import Player from '../components/Player';


let socket;
const Home: NextPage = () => {
  useEffect(() => {
    socketInitializer();
  }, [])

  const socketInitializer = async () => {
    await fetch('/api/socket');
    socket = SocketIO();

    socket.on('connect', () => {
      console.log('connected')
    })
    return null;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <video src=""></video> */}
        <Player />
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
